[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor --chip esp32s2"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[env]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s2-none-elf"

[unstable]
build-std = ["core"]
